CREATE DATABASE MrPeter;

USE MrPeter;

CREATE TABLE faculty(
	ID INT NOT NULL PRIMARY KEY IDENTITY,
	fName NVARCHAR(20),
	school NVARCHAR(20),
	fPassword NVARCHAR(20)
);

CREATE TABLE student(
	ID INT NOT NULL PRIMARY KEY IDENTITY,
	sName NVARCHAR(20),
	school NVARCHAR(20),
);

TOP DATABASE MrPeter;